-- INSERT comments
INSERT INTO resource_comments (guest_id, resource_id, comments, timestamp)
VALUES (1, 1, 'good comment', current_timestamp),
       (2, 2, 'alright comment', current_timestamp),
       (3, 3, 'gnarly comment', current_timestamp),
       (4, 4, 'spectacular comment', current_timestamp),
       (3, 5, 'bad comment', current_timestamp),
       (4, 6, 'aggressive comment', current_timestamp),

       (1, 7, 'satisfactory comment', current_timestamp),
       (2, 8, 'adequate comment', current_timestamp),
       (3, 9, 'so-so comment', current_timestamp),
       (4, 10, 'substandard comment', current_timestamp),
       (3, 11, 'atrocious comment', current_timestamp),
       (4, 12, 'diabolical comment', current_timestamp),

       (1, 13, 'abysmal comment', current_timestamp),
       (2, 14, 'sensational comment', current_timestamp),
       (3, 15, 'magnificent comment', current_timestamp),
       (4, 16, 'marvelous comment', current_timestamp),
       (3, 17, 'nifty comment', current_timestamp),
       (4, 18, 'boss comment', current_timestamp),

       (1, 19, 'combative comment', current_timestamp),
       (2, 20, 'contentious comment', current_timestamp),
       (3, 21, 'fantastic comment', current_timestamp),
       (4, 22, 'razzly-dazzly comment', current_timestamp),
       (3, 23, 'amazing comment', current_timestamp),
       (4, 24, 'stupendous comment', current_timestamp),

       (1, 25, 'scandalous comment', current_timestamp),
       (2, 26, 'buy my self-help book comment', current_timestamp),
       (3, 27, 'follow this link for free money comment', current_timestamp),
       (4, 28, 'godawful comment', current_timestamp),
       (3, 29, 'fiendish comment', current_timestamp),
       (4, 30, 'aggressive comment', current_timestamp),

       (1, 31, 'troll comment', current_timestamp),
       (2, 32, 'grody comment', current_timestamp),
       (3, 33, 'cursed comment', current_timestamp),
       (4, 34, 'raunchy comment', current_timestamp),
       (3, 35, 'HUGE comment', current_timestamp),
       (4, 36, 'I leave absoultely the best most tremendous comments', current_timestamp),

       (1, 1, 'abysmal comment', current_timestamp),
       (2, 1, 'sensational comment', current_timestamp),
       (3, 1, 'magnificent comment', current_timestamp),
       (4, 2, 'marvelous comment', current_timestamp),
       (3, 2, 'nifty comment', current_timestamp),
       (4, 2, 'boss comment', current_timestamp);
